function [Data]=Notch_Filter_Gaussian(Image,k)
%%
bandwidth=1e3;
Dimensions=size(Image);
u1=k*Dimensions(1);
u2=(1-k)*Dimensions(1);
v1=k*Dimensions(2);
v2=(1-k)*Dimensions(2);
%%
U=1:Dimensions(1);
V=1:Dimensions(2);
[DD1,DD2]=meshgrid(U,V);
%%
temp1=(DD1-u1).^2;
temp2=(DD2-v1).^2;
temp11=temp1./2/bandwidth;
temp22=temp2./2/bandwidth;
G1=exp(-(temp11+temp22));
%%
temp3=(DD1-u2).^2;
temp4=(DD2-v2).^2;
temp11=temp3./2/bandwidth;
temp22=temp4./2/bandwidth;
G2=exp(-(temp11+temp22));
%%
G=1-(G1+G2);
Image_Spectrum=fftshift(fft2(Image));
Image_Filtered_Spectrum=Image_Spectrum.*G;
Image_Filtered=abs(ifft2(Image_Filtered_Spectrum));
Data.Image_Filtered=Image_Filtered;
Data.Image_Filtered_Spectrum=Image_Filtered_Spectrum;
Data.G=G;
%%
end