#!/usr/bin/env python

import numpy as np

def IndexOfMax(a):
	a = np.array([[1,2,3],[4,3,1]])
	Index = np.unravel_index(a.argmax(), a.shape)
	return Index;


a = np.array([[1,2,3],[4,3,1]])
i,j = np.unravel_index(a.argmax(), a.shape)
print a
print a[i,j]
print IndexOfMax(a)

